import Head from "next/head";
const Layout =(props:any) => {
  return (
    <div className="container">
      <Head>
        <title>Examen Practico</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.children}
    </div>
  )
}

export default Layout;